### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by MingweiSamuel** [jessehallam/RedditRankedFlairs#2]
What licence is this project under? Or is it _proprietary_ :fearful:

**Comment by jessehallam** [comment]
Hi there. Feel free to treat it as public domain. Licenses for libraries
(as noted in
https://github.com/jessehallam/RedditRankedFlairs/blob/Production/README.md)
are their owners respective licenses.

**Comment by MingweiSamuel** [comment]
Thanks
